version: '3.3'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./nginx/config:/etc/nginx/conf.d/
      - ../:/var/www
    ports:
      - '80:80'
      - '443:443'
    links:
      - php
    restart: always
  php:
    container_name: php
    build: ./php-fpm
    volumes:
      - ./php-fpm/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../:/var/www
    links:
      - mysql
    restart: always
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./mysql/config/docker.cnf:/etc/mysql/conf.d/docker.cnf
      - ./mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    restart: always
